<a href="https://colab.research.google.com/github/elmago07/AI-ML-Learnings/blob/main/pandas_learnings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
######Tow data structures in pandas:series and DataFrame######

In [ ]:
import pandas as pd
###creating a series from a list###
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
####Data FRame###

data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris']}
df = pd.DataFrame(data)
print(df)

      Team          Driver
0  Redbull  Max Verstappen
1   Ferrai        Hamilton
2  McLaren    Lando Norris

In [ ]:
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

In [ ]:
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df.size)
print(df.ndim)
print(df.shape)

12
2
(3, 4)

In [9]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df.index)
print(df.columns)
print(df.values)
print(df.axes)
print(df.dtypes)

RangeIndex(start=0, stop=3, step=1)
Index(['Team', 'Driver', 'Tyre', 'Power_Unit'], dtype='object')
[['Redbull' 'Max Verstappen' 'hard' 'Honda']
 ['Ferrai' 'Hamilton' 'soft' 'Ferrari']
 ['McLaren' 'Lando Norris' 'soft' 'Mercedes']]
[RangeIndex(start=0, stop=3, step=1), Index(['Team', 'Driver', 'Tyre', 'Power_Unit'], dtype='object')]
Team          object
Driver        object
Tyre          object
Power_Unit    object
dtype: object

In [10]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df.info() #gives the entire data of data frame instead of calling one one method everyttime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Team        3 non-null      object
 1   Driver      3 non-null      object
 2   Tyre        3 non-null      object
 3   Power_Unit  3 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes

In [12]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df.describe() #gives basic statics of data

           Team          Driver  Tyre Power_Unit
count         3               3     3          3
unique        3               3     2          3
top     Redbull  Max Verstappen  soft      Honda
freq          1               1     2          1

In [14]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df.memory_usage() #gives memeory usage of each column

Index         132
Team           24
Driver         24
Tyre           24
Power_Unit     24
dtype: int64

In [18]:
# Accessing data in data frame
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
#df.Team
df.Driver

0    Max Verstappen
1          Hamilton
2      Lando Norris
Name: Driver, dtype: object

In [30]:
### Acessing rows using iloc and loc
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df)
df.iloc[0:2] #Access row by position using iloc

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari

In [26]:
### Acessing rows using iloc and loc
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df)
df.loc[0:2] ##access row by label using loc

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes